package com.deameamo.rst

object Command {
  val OPEN = "OPEN"
  val EXIT = "EXIT"
  val CLEAR_TREE = "CLEAR_TREE"
  val SEARCH_TREE = "SEARCH_TREE"
  val CLEAR_EDITOR = "CLEAR_EDITOR"
  val SEARCH_EDITOR = "SEARCH_EDITOR"
  
  val STANDARDIZE = "STANDARDIZE"
  
  val ADD = "ADD"
  
  val EDITOR_REMOVE_WORD = "EDITOR_REMOVE_WORD"
  val EDITOR_ADD_WORD = "EDITOR_ADD_WORD"
//  val EDITOR_REMOVE_CHAIN = "EDITOR_REMOVE_CHAIN"
  val EDITOR_ADD_CHAIN = "EDITOR_ADD_CHAIN"
  
  val SYNCH = "SYNCH"
  val SYNCHED = "SYNCHED"
  
  val SAVE = "SAVE"
  val EXPORT_RULES = "EXPORT_RULES"
  val EXPORT_CONJUNCTIONS = "EXPORT_CONJUNCTIONS"
  
  val UNDO = "UNDO"
  val DONE = "DONE"
  
  val SWITCH = "SWITCH"
  
  val FILE_LOADED = "FILE_LOADED"
  val RESOURCE_LOADED = "RESOURCE_LOADED"
  
  val TREE_MODEL_CHANGED = "TREE_MODEL_CHANGED"
  val TREE_MODEL_SYNCHED = "TREE_MODEL_SYNCHED"
  
  val LIST_EMPTIED = "LIST_EMPTIED"
  
  val SHOW_CONTRADICTS = "SHOW_CONTRADICTS"
  
  val AUTO_CHECK_CHANGED = "AUTO_CHECK_CHANGED"
  
  val LEXICAL_CHAIN_INSTANCE_ADDED = "LEXICAL_CHAIN_INSTANCE_ADDED"
  val LEXICAL_CHAIN_INSTANCE_DELETED = "LEXICAL_CHAIN_INSTANCE_DELETED"
  val LEXICAL_CHAIN_INSTANCE_SELECTED = "LEXICAL_CHAIN_INSTANCE_SELECTED"
  
  val LEXICAL_CHAIN_SELECTED = "LEXICAL_CHAIN_SELECTED"
  
  val PATTERN_TREE_DATA_CHANGED = "PATTERN_TREE_DATA_CHANGED"
  
  val LEXICAL_CHAIN_INSTANCE_VIEWED = "LEXICAL_CHAIN_INSTANCE_VIEWED"
  
  val SEARCH_POSITIONS = "SEARCH_POSITIONS"
  
  val SET_STATUS = "SET_STATUS"
  
  val TEXT_SPAN_DELETED = "TEXT_SPAN_DELETED"
  
  val PATTERN_TREE_ADJUSTED = "PATTERN_TREE_ADJUSTED"
  
  val DELETE_POSITION = "DELETE_POSITION"
  
  val SEARCH_RELATIONS = "SEARCH_RELATIONS"
  val RELATION_NODE_VIEWED = "RELATION_NODE_VIEWED"
}

case class ChangeMessage(listName: String, word: String)

case class FileLoadedMessage(position: LexicalChainPosition, relationNode: RelationNode)